language: java
notifications:
  email:
    recipients:
      - mateuszollek@gmail.com
      - matylaolga@gmail.com
      #uzupełnijcie tutaj
    on_success: never # default: change
    on_failure: always # default: always 

after_success:
- mvn --quiet clean site 

before_deploy:
  - "mvn -DskipTests package"

deploy:
  provider: releases
  api_key: $github_token
  skip_cleanup: true
  file: target/text-transformer-klient.jar
  on:
    tags: true
