language: java
notifications:
  email:
    recipients:
      - mateuszollek@gmail.com
      - matylaolga@gmail.com
      #uzupełnijcie tutaj
    on_success: never # default: change
    on_failure: always # default: always 

after_success:
- mvn --quiet clean site 

